### ISSUE TITLE
输入https://www.douyin.com/user/MS4wLjABAAAAK8yyhMzdNAtyWqupVvVBXB_4bmr6DMAZ0zpGn91qlJU?vid=7124859220079561995地址之后报错

### ISSUE THREAD

**Issue by samuncle** [zouzanyan/douyin_crawl#8]
Traceback (most recent call last):
  File "/Users/apple/Downloads/douyin_crawl-main/CrawlHome.py", line 157, in <module>
    c.get_home_video(user_in)
  File "/Users/apple/Downloads/douyin_crawl-main/CrawlHome.py", line 79, in get_home_video
    cursor = json_str["max_cursor"]  # 当页页码
KeyError: 'max_cursor'

**Comment by zouzanyan** [comment]
![image](https://github.com/zouzanyan/douyin_crawl/assets/68853552/ba959ce4-896a-4b36-916c-90561a318158)
检查一下cookie配置，我这里可以正常下载

**Comment by sgggp** [comment]
cookie配置怎么检查，我是  cursor = json_str["max_cursor"]  # 当页页码
             ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'max_cursor'
这种报错，跑不起来

**Comment by SevenOfPaul** [comment]
报错同上

**Comment by zouzanyan** [comment]
> 报错同上



> cookie配置怎么检查，我是 cursor = json_str["max_cursor"] # 当页页码 ~~~~~~~~^^^^^^^^^^^^^^ KeyError: 'max_cursor' 这种报错，跑不起来

最近将修复

**Comment by zouzanyan** [comment]
目前正常
